<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aleksi Ikkala">
<meta name="dcterms.date" content="2026-05-25">
<meta name="description" content="We train a 3B language model to express calibrated confidence using GRPO, then look inside to understand what changes. The main finding: the model already knew what it didn’t know – it just couldn’t say so.">

<title>Do LLMs Know What They Don’t Know? Teaching Confidence with RL – Residual Thoughts</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-331377c7eeb781c14d37823ec42e9306.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Residual Thoughts</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Residual Thoughts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Do LLMs Know What They Don’t Know? Teaching Confidence with RL</h1>
                  <div>
        <div class="description">
          We train a 3B language model to express calibrated confidence using GRPO, then look inside to understand what changes. The main finding: the model already knew what it didn’t know – it just couldn’t say so.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">calibration</div>
                <div class="quarto-category">reinforcement-learning</div>
                <div class="quarto-category">mechanistic-interpretability</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Aleksi Ikkala </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 25, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>Large language models can be prompted to explicitly express confidence in their answers. However, the expressed confidence may not correlate with correctness of the answers: Ask a 3B model who directed an obscure 1970s film and it might answer with the same assured tone as when you ask it the capital of France. This is miscalibration – a mismatch between expressed and warranted confidence – and it’s a fundamental problem for any system that needs to communicate its own reliability.</p>
<p>The interesting question isn’t just <em>can we fix this</em> but <em>why does it happen in the first place?</em> Two very different accounts are possible:</p>
<ol type="1">
<li><strong>Representation failure</strong>: the model simply doesn’t know what it doesn’t know – the uncertainty information isn’t in the model at all, and training on confidence labels can’t create it from scratch.</li>
<li><strong>Expression failure</strong>: the model <em>does</em> have the relevant internal signal, but lacks a mechanism to translate it into a confidence output.</li>
</ol>
<p>These have different implications. If it’s a representation problem, there’s not much we could do apart from training a bigger model with more capacity to store factual knowledge. If it’s an expression problem, targeted training may be enough to calibrate the model to translate uncertainty into the expressed confidence value. This post describes an experiment that tried to find out which one it is.</p>
<section id="the-setup" class="level2">
<h2 class="anchored" data-anchor-id="the-setup">The Setup</h2>
<p>We finetuned Llama3.2-3B-Instruct using <a href="https://arxiv.org/abs/2402.03300">GRPO</a> with a reward structure that directly incentivises calibrated confidence. For each question, the model had to produce a JSON array:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ot">[</span><span class="st">"high"</span><span class="ot">,</span> <span class="st">"Paris"</span><span class="ot">]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>where the first element is its confidence (<code>"high"</code> or <code>"low"</code>), and the second is its answer. We then rewarded or penalised based on whether it was right and how confident it claimed to be:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>High confidence</th>
<th>Low confidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Correct</strong></td>
<td>+2</td>
<td>+1</td>
</tr>
<tr class="even">
<td><strong>Incorrect</strong></td>
<td>−2</td>
<td>−1</td>
</tr>
<tr class="odd">
<td><strong>Unparseable</strong></td>
<td>−1.5</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>High confidence is the rational choice when the model expects to be right more than 50% of the time. An unparseable output gets −1.5 – worse than a low-confidence wrong answer – so the model won’t learn to output arbitrary outputs.</p>
<p>We trained on <a href="https://arxiv.org/abs/2212.10511">PopQA</a>, a factual QA dataset built from Wikidata with entity popularity scores that serve as a natural difficulty proxy. One important practical finding: training data difficulty acts as an implicit regulariser. Training on questions the model almost always gets right causes it to collapse to always saying “high confidence”; training on questions it almost never gets right causes it to always say “low confidence”. We found the sweet spot at <code>min_popularity=20,000</code>, where training accuracy sits around 30–40%. Training at <code>min_popularity=50,000</code> (easier questions) produced a finetuned model with ECE 0.49 – nearly identical to the untrained base model.</p>
<p>We also tested two baselines using the base model without finetuning: <strong>direct prompting</strong> (same JSON format, no reasoning) and <strong>chain-of-thought prompting</strong> (CoT; brief reasoning before the answer).</p>
</section>
<section id="behavioral-results" class="level2">
<h2 class="anchored" data-anchor-id="behavioral-results">Behavioral Results</h2>
<p>Averaged across three random seeds:</p>
<p><strong>PopQA (in-distribution)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Base direct</th>
<th>Base CoT</th>
<th>Finetuned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ECE ↓</td>
<td>0.525 ± 0.014</td>
<td>0.324 ± 0.023</td>
<td><strong>0.069 ± 0.007</strong></td>
</tr>
<tr class="even">
<td>Accuracy ↑</td>
<td>0.165 ± 0.003</td>
<td><strong>0.201 ± 0.002</strong></td>
<td><strong>0.201 ± 0.005</strong></td>
</tr>
<tr class="odd">
<td>High-conf accuracy ↑</td>
<td>0.194 ± 0.007</td>
<td>0.294 ± 0.010</td>
<td><strong>0.603 ± 0.013</strong></td>
</tr>
<tr class="even">
<td>High-conf rate</td>
<td>0.735 ± 0.021</td>
<td>0.531 ± 0.028</td>
<td>0.202 ± 0.007</td>
</tr>
<tr class="odd">
<td>Calibration gap ↑</td>
<td>0.107 ± 0.031</td>
<td>0.196 ± 0.006</td>
<td><strong>0.503 ± 0.023</strong></td>
</tr>
</tbody>
</table>
<p>ECE (expected calibration error) drops 87% from base to finetuned. But the more interpretable number is what happens to <em>high-confidence predictions</em>: the base model says “high confidence” on 73.5% of questions and is right on 19.4% of them. The finetuned model says “high confidence” on just 20.2% of questions — and is right on 60.3% of them. It learned to be selective.</p>
<p>The calibration gap (accuracy on high-conf predictions minus accuracy on low-conf predictions) grows nearly five-fold: 0.107 -&gt; 0.503. This implies the model learns that its confidence label actually means something.</p>
<p>The popularity quartile breakdown is particularly clean — the finetuned model’s high-confidence rate tracks its actual accuracy across difficulty levels:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quartile</th>
<th>Accuracy</th>
<th>High-conf rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Q1 (hardest)</td>
<td>12.9% ± 0.5%</td>
<td>8.6% ± 0.3%</td>
</tr>
<tr class="even">
<td>Q2</td>
<td>8.8% ± 1.8%</td>
<td>12.2% ± 1.3%</td>
</tr>
<tr class="odd">
<td>Q3</td>
<td>15.5% ± 2.4%</td>
<td>15.2% ± 1.3%</td>
</tr>
<tr class="even">
<td>Q4 (easiest)</td>
<td>43.2% ± 2.3%</td>
<td>44.5% ± 3.1%</td>
</tr>
</tbody>
</table>
<p>The base model maintains 58–78% high-confidence rates regardless of difficulty.</p>
<p><strong>Does it generalise?</strong></p>
<p>We tested on TriviaQA without any further training:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Base direct</th>
<th>Base CoT</th>
<th>Finetuned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ECE ↓</td>
<td>0.322 ± 0.003</td>
<td><strong>0.293 ± 0.024</strong></td>
<td><strong>0.290 ± 0.010</strong></td>
</tr>
<tr class="even">
<td>Accuracy ↑</td>
<td>0.511 ± 0.005</td>
<td><strong>0.538 ± 0.019</strong></td>
<td><strong>0.532 ± 0.020</strong></td>
</tr>
<tr class="odd">
<td>High-conf accuracy ↑</td>
<td>0.550 ± 0.004</td>
<td><strong>0.591 ± 0.027</strong></td>
<td><strong>0.602 ± 0.018</strong></td>
</tr>
<tr class="even">
<td>High-conf rate</td>
<td>0.892 ± 0.012</td>
<td>0.798 ± 0.004</td>
<td>0.700 ± 0.022</td>
</tr>
<tr class="odd">
<td>Calibration gap ↑</td>
<td><strong>0.366 ± 0.043</strong></td>
<td>0.262 ± 0.042</td>
<td>0.232 ± 0.026</td>
</tr>
</tbody>
</table>
<p>The ECE improvement is modest (0.322 -&gt; 0.290) compared to PopQA, and calibration gap decreases (0.366 -&gt; 0.232). Furthermore, CoT achieves comparable calibration to the finetuned model (ECE 0.293 vs 0.290). This indicates that the finetuned model’s calibration behavior does not strongly generalise beyond its training distribution. PopQA’s entity-centric format and popularity-correlated difficulty may allow the model to learn confidence signals tied to detectable surface features (such as entity name familiarity) that do not transfer to TriviaQA’s more varied question distribution, where correctness is harder to predict from any single input feature.</p>
<p><strong>Accuracy as a side effect</strong></p>
<p>A somewhat surprising finding: calibration training also improved factual accuracy on PopQA by +3.5% ± 0.8%, statistically significant in all three seeds (McNemar’s test, p &lt; 0.005). The effect is concentrated in higher-popularity questions (+7.1% in Q4 vs +1.9% in Q1) and is absent on TriviaQA (McNemar’s test, p=286). This is consistent with RL training improving factual recall as a side effect – a pattern also observed in <a href="https://arxiv.org/abs/2402.03300">DeepSeek-R1</a> for reasoning tasks.</p>
</section>
<section id="whats-happening-inside" class="level2">
<h2 class="anchored" data-anchor-id="whats-happening-inside">What’s Happening Inside?</h2>
<p>We trained linear probes on the residual stream activations at the position of the final prompt token – the point right before the model starts generating – for all 28 layers of both the base and finetuned models. This approach is similar to that presented in <a href="https://arxiv.org/abs/2304.13734">Azaria &amp; Mitchell, 2023</a>, where they trained classifiers to predict the correctness of a statement based on hidden layer activations.</p>
<p>The question: does the internal representation predict whether the model will get the answer right, and does this change after finetuning?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="probe_results.png" class="img-fluid figure-img"></p>
<figcaption>Probe AUC across transformer layers for base model, finetuned model, and cross-dataset transfer (train on PopQA, test on TriviaQA).</figcaption>
</figure>
</div>
<p><strong>The base model already knows.</strong> Probe AUC rises from 0.70 at layer 0 to a broad plateau of ~0.85–0.86 from layer 11 onwards. Before any calibration training, the model’s internal representations are already strongly predictive of whether it will answer correctly. The uncertainty information is there – the model just doesn’t express it.</p>
<p><strong>Finetuning reduces linear probe AUC.</strong> The finetuned model shows consistently lower probe AUC, especially across later layers, a gap of about 0.05 relative to the base model. This is the surprising result: dramatically better behavioral calibration (ECE 0.069 vs 0.525) is accompanied by <em>less</em> linearly separable internal representations. The correctness-predictive information becomes harder to decode with a linear probe, yet the model’s outputs become much better calibrated.</p>
<p>This suggests calibration training reorganises how uncertainty information is encoded and used, rather than simply amplifying an existing signal. The finetuning changes the representational geometry in a way that’s less decodable by a logistic probe but more functionally coupled to the confidence output. Why? A few possibilities:</p>
<ul>
<li>The uncertainty signal gets encoded in a more nonlinear or distributed form after finetuning, harder for a linear probe to capture but accessible to the model’s own attention and feedforward mechanisms.</li>
<li>GRPO training partially “uses up” the correctness-predictive signal by routing it through the confidence output, leaving a weaker residual in the activations.</li>
<li>The probe captures both genuine uncertainty information and question-difficulty surface features; finetuning on filtered training data (<code>min_popularity ≥ 20,000</code>) selectively reduces the surface-feature component.</li>
</ul>
<p>Distinguishing between these would require causal intervention experiments, e.g., activation patching to test whether specific layer activations causally influence the confidence output. Perhap’s we’ll get to that at some point.</p>
<p><strong>Does the representation generalise across datasets?</strong></p>
<p>We trained probes on PopQA activations and evaluated on TriviaQA activations (with the test set downsampled to match the 15% PopQA positive rate). Cross-dataset AUC peaks (&gt;0.6) in mid-layers (11–19), with near-chance performance in the first 7 layers. The early-layer signal doesn’t transfer – it’s capturing PopQA-specific question features. The mid-layer signal generalises, consistent with those layers encoding more abstract semantic content.</p>
</section>
<section id="what-this-means" class="level2">
<h2 class="anchored" data-anchor-id="what-this-means">What This Means</h2>
<p>The central finding is that miscalibration in this 3B model is, to a large extent, a <strong>failure of expression, not representation</strong>. The model knows what it doesn’t know – the information is in the residual stream – but without targeted training it can’t translate that signal into its outputs.</p>
<p>GRPO with calibration rewards installs this translation mechanism. But it does so by reorganising internal representations rather than amplifying them, which raises new questions about the nature of learned confidence.</p>
<p>A few practical takeaways:</p>
<ul>
<li><strong>Training data difficulty is a critical hyperparameter</strong> for calibration training. Questions that are too easy lead to confidence values that are always high. Questions that are too hard lead to confidence values that are always low. The reward function alone doesn’t determine the dynamics; the difficulty distribution of training data interacts with it.</li>
<li><strong>CoT prompting is a reasonable calibration intervention</strong> when models have meaningful domain knowledge (~40–60% accuracy). For harder tasks at the edges of model knowledge, finetuning is needed.</li>
<li><strong>The base model’s residual stream already contains correctness-predictive information</strong> that could in principle be extracted with a linear probe, without any finetuning. This enables deployment-time confidence estimation that doesn’t require any model modification.</li>
</ul>
</section>
<section id="limitations-and-future-work" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-future-work">Limitations and Future Work</h2>
<ul>
<li>All experiments use a single 3B model, so scale generalisation is unknown.</li>
<li>The binary confidence format is a significant simplification – three or more bins would require non-trivial reward design to prevent the model from using intermediate bins as a hedge.</li>
<li>The probe AUC decrease interpretation is correlational; causal intervention experiments would provide stronger evidence.</li>
</ul>
<p>The most interesting open question is the mechanism behind the probe AUC decrease. Activation patching experiments could establish whether specific layers causally drive the confidence output, and nonlinear probes could test whether the uncertainty information is present but nonlinearly encoded after finetuning. If either finds a clean answer, it would meaningfully advance our understanding of how calibration training works mechanistically.</p>
<hr>
<p><em>Code is available at <a href="https://github.com/aikkala/llm-calibration">github.com/aikkala/llm-calibration</a>. Questions and feedback welcome.</em></p>



</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aikkala\.github\.io\/residual-thoughts");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>